#!/usr/bin/env python3

# The purpose of this script is simply to convert jtr style NETNTLM hashes to a format understood by hashcat
# INPUT: something like the logs generated by hostapd-wpe
#   With lines like "jtr NETNTLM: USERNAME:$NETNTLM$SALT$HASH
# OUTPUT: USERNAME::::HASH:SALT

import sys

def convert(line):
  arr = line.split('$')
  user = arr[0].split(':')[1].strip()
  return "{}::::{}:{}".format(user, arr[3].strip(), arr[2].strip())

file = sys.stdin
if (len(sys.argv) > 1 ) :
  path = sys.argv[1]
  file = open(path, 'r')
for line in file  
  if "jtr" in line:
    print(convert(line))
